- src/main/java/com/fivet/buddy/controller/MemberController.java
- src/main/java/com/fivet/buddy/dao/MemberDAO.java
- src/main/java/com/fivet/buddy/mapper/MemberMapper.java
- src/main/java/com/fivet/buddy/services/MemberService.java
- src/main/resources/mappers/member-mapper.xml
- src/main/resources/static/css/m-mypage.css
- src/main/resources/static/css/mypage.css
- src/main/resources/static/css/myprofile.css
- src/main/resources/templates/index.html
- src/main/resources/templates/myprofile.html
Fix : (myprofile.html) 휴대전화 변경 추가, (MemberController.java,MemberDAO.java, MemberMapper.java, member-mapper.xml, MemberService.java) 휴대전화 변경 추가 / Style : (mypage.css) 휴대전화 변경 틀만 잡아둠 아직 미완성) / Renam
e : (MemberController.java, index.html) myProfile -> goMyProfile로 이름변경해서 index.html의 location.href 주소값도 이름 변경
> (ver 1.8.0) 마이프로필페이지에서 휴대전화 변경 추가

- build.gradle
- src/main/java/com/fivet/buddy/controller/MemberController.java
- src/main/java/com/fivet/buddy/dao/MemberDAO.java
- src/main/java/com/fivet/buddy/dto/MemberImgDTO.java
- src/main/java/com/fivet/buddy/mapper/MemberMapper.java
- src/main/java/com/fivet/buddy/services/MemberService.java
- src/main/resources/mappers/member-mapper.xml
- src/main/resources/static/css/myProfile.css
- src/main/resources/templates/member/myProfile.html
Fix : (member-mapper.xml,MemberController.java,MemberDAO.java,MemberMapper.java,MemberService.java,
myProfile.html,myProfile.css) 회원탈퇴 기능 추가 (css 미완성) / New : (MemberImgDTO.java) 프로필 이미지 DTO 생성 / Test : (build.gradle, MemberController.java) 프로필 이미지 변경 테스트중 (주석처리 해둠)
> (ver 1.13.0) Fix : 회원탈퇴 기능 추가 / Test : 프로필 이미지 테스트중

- src/main/java/com/fivet/buddy/config/FileHandler.java
- src/main/java/com/fivet/buddy/util/FileUtil.java
- src/main/resources/application.properties
application.properties 파일에 파일 크기 및 파일 경로 추가(ver을 실수로 넣었음)
파일관련기능 Util파일 추가 DB기능과 분리됨
이미지 파일 외부 경로(프로젝트 외부 경로 ex)C:/files/)에서 읽어 올 수 있는 FileHandler기능 추가
> (ver 3.3.0) Feat : 파일관련 기능 추가

- src/main/java/com/fivet/buddy/util/FileUtil.java
- src/main/resources/application.properties
Fix : 경로수정
Feat : 파일 다운로드 기능 추가
> (ver 3.4.2)Feat : 파일 다운로드 기능 추가

- src/main/java/com/fivet/buddy/controller/TeamController.java
- src/main/java/com/fivet/buddy/dao/TeamDAO.java
- src/main/java/com/fivet/buddy/mapper/TeamMapper.java
- src/main/java/com/fivet/buddy/services/TeamService.java
- src/main/resources/mappers/team-mapper.xml
- src/main/resources/static/css/teamSetting.css
- src/main/resources/templates/index.html
- src/main/resources/templates/team/teamSetting.html
Feat : (team-mapper.xml, TeamController.java, TeamDAO.java, TeamMapper.java, TeamService.java, teamSetting.css, teamSetting.html) 팀 이름 수정 추가 / Refactor : (index.html) th:name -> name으로 수정 / Test : (team-mapper.xml, TeamController.java, TeamDAO.java, TeamMapper.java, TeamService.java, teamSetting.css, teamSetting.html) 팀 관리 테스트중
> (ver 4.1.0) Feat : 팀 관리에서 팀 이름 변경 추가 / Test : 팀 삭제 테스트 중

- src/main/java/com/fivet/buddy/controller/TeamController.java
- src/main/java/com/fivet/buddy/services/TeamService.java
- src/main/resources/templates/team/teamSetting.html
Feat : (teamSetting.html) 팀 삭제 추가 / Docs : (TeamService.java, TeamController.java) : sysout 삭제
> (ver 4.6.0) Feat : 팀 삭제 추가

- src/main/resources/static/css/customer.css
- src/main/resources/static/css/customerPopup.css
- src/main/resources/static/css/m-customer.css
- src/main/resources/templates/customer/customer.html
- src/main/resources/templates/customer/customerPopup.html
ver 4.7.0 상세내용
1. 고객센터 페이지
- 목록은 1:1 문의 와 공지사항 으로 구성되어 있습니다
- 업데이트 항목은 실제로는 동작하지 않는 탭입니다. (구성을 맞추기 위한 더미오브젝트)
2. 글쓰기
- 화면은 팝업으로 뜸
3. Ajax
- 모든 목록은 ajax 로 주고받게 프론트작업이 되어있습니다.
> (ver 4.7.0) New : customer 페이지 추가 

- src/main/java/com/fivet/buddy/controller/MemberController.java
- src/main/java/com/fivet/buddy/dao/MemberDAO.java
- src/main/java/com/fivet/buddy/mapper/MemberMapper.java
- src/main/java/com/fivet/buddy/services/MemberService.java
- src/main/resources/mappers/member-mapper.xml
- src/main/resources/templates/member/myProfile.html
- src/main/resources/templates/team/teamSetting.html
Fix : 마이프로필 프로필 이미지 수정 경로 수정
Fix : 마이프로필 프로필 이미지 이벤트 무한 발동 수정
> Fix : 마이프로필 프로필 이미지 버그 수정

- src/main/java/com/fivet/buddy/controller/NoticeController.java
- src/main/java/com/fivet/buddy/controller/QnaController.java
- src/main/java/com/fivet/buddy/dao/NoticeDAO.java
- src/main/java/com/fivet/buddy/dao/NoticeFileDAO.java
- src/main/java/com/fivet/buddy/dao/QnaCommentDAO.java
- src/main/java/com/fivet/buddy/dao/QnaDAO.java
- src/main/java/com/fivet/buddy/dao/QnaFileDAO.java
- src/main/java/com/fivet/buddy/dto/NoticeDTO.java
- src/main/java/com/fivet/buddy/dto/NoticeFileDTO.java
- src/main/java/com/fivet/buddy/dto/QnaCommentDTO.java
- src/main/java/com/fivet/buddy/dto/QnaDTO.java
- src/main/java/com/fivet/buddy/dto/QnaFileDTO.java
- src/main/java/com/fivet/buddy/mapper/NoticeMapper.java
- src/main/java/com/fivet/buddy/mapper/QnaMapper.java
- src/main/java/com/fivet/buddy/services/NoticeFileService.java
- src/main/java/com/fivet/buddy/services/NoticeService.java
- src/main/java/com/fivet/buddy/services/QnaCommentService.java
- src/main/java/com/fivet/buddy/services/QnaFileService.java
- src/main/java/com/fivet/buddy/services/QnaService.java
- src/main/resources/mappers/notice-mapper.xml
- src/main/resources/mappers/qna-mapper.xml
- src/main/resources/static/css/customer.css
- src/main/resources/templates/customer/customer.html
- src/main/resources/templates/customer/customerPopup.html
- src/main/resources/templates/team/team.html
[Feat : 문의하기 기능 추가]
[Feat : 공지사항 및 뉴스 기능 추가]
[Style : 문의하기 및 뉴스 css 코드 수정 및 team.html 문의하기로 이동 코드 추가]
> Feat : 문의하기 및 업데이트사항(뉴스) 기능추가

- src/main/java/com/fivet/buddy/controller/TeamController.java
- src/main/resources/templates/team/teamSetting.html
Refactor : 멤버 등급 관련 리팩토링 manager -> 매니저로 변경
> (ver 5.4.1) Refactor : 멤버 등급 관련 리팩토링 manager -> 매니저로 변경

- src/main/java/com/fivet/buddy/controller/TeamController.java
- src/main/resources/templates/team/team.html
- src/main/resources/templates/team/teamChating.html
- src/main/resources/templates/team/teamTemplate.html
Feat : 팀원 목록 출력 기능 추가 / Refactor : 팀원 목록 출력 ajax에 쓰이는 let MemberImg -> let JsonTeamMemberList로 이름 변경
> (ver 5.7.0) Feat : 팀원 목록 출력 기능 추가 / Refactor : 팀원 목록 출력 ajax에 쓰이는 let MemberImg -> let JsonTeamMemberList 로 이름 변경

- src/main/java/com/fivet/buddy/controller/MemberController.java
- src/main/java/com/fivet/buddy/dao/TeamMemberDAO.java
- src/main/java/com/fivet/buddy/mapper/TeamMemberMapper.java
- src/main/java/com/fivet/buddy/services/TeamMemberService.java
- src/main/resources/mappers/teamMember-mapper.xml
- src/main/resources/templates/index.html
Fix : team_member 테이블에 부매니저 등급이 아예 없을때 오류 처리
> (ver 5.9.0) Fix : team_member 테이블에 부매니저 등급이 아예 없을때 오류 처리

- src/main/java/com/fivet/buddy/controller/DriveController.java
- src/main/java/com/fivet/buddy/controller/MemberController.java
- src/main/java/com/fivet/buddy/dao/BasicFolderDAO.java
- src/main/java/com/fivet/buddy/dao/PersonalFileDAO.java
- src/main/java/com/fivet/buddy/dao/PersonalFolderDAO.java
- src/main/java/com/fivet/buddy/mapper/BasicFolderMapper.java
- src/main/java/com/fivet/buddy/mapper/PersonalFileMapper.java
- src/main/java/com/fivet/buddy/mapper/PersonalFolderMapper.java
- src/main/java/com/fivet/buddy/services/BasicFolderService.java
- src/main/java/com/fivet/buddy/services/PersonalFileService.java
- src/main/java/com/fivet/buddy/services/PersonalFolderService.java
- src/main/java/com/fivet/buddy/util/FileUtil.java
- src/main/resources/mappers/basicFolder-mapper.xml
- src/main/resources/mappers/personalFlie-mapper.xml
- src/main/resources/mappers/personalFolder-mapper.xml
- src/main/resources/templates/drive/detailDrive.html
- src/main/resources/templates/drive/fileDrive.html
bug :  파일이나 폴더를 삭제하면 차감되는 용량이 중복으로 적용되어 db에 null로 반영됨. >> long 자료형이 null을 받을 수 없어 drive접속이 막힘
> (ver 6.1.0) 회원 탈퇴시 폴더 및 파일 삭제, DB drive정보 제거, 회원별 용량 관련 버그 fix

- src/main/java/com/fivet/buddy/controller/ChatRoomController.java
- src/main/java/com/fivet/buddy/controller/EmoticonController.java
- src/main/java/com/fivet/buddy/dao/ChatMemberDAO.java
- src/main/java/com/fivet/buddy/dao/EmoticonDAO.java
- src/main/java/com/fivet/buddy/dto/ChatMemberListDTO.java
- src/main/java/com/fivet/buddy/mapper/ChatMemberMapper.java
- src/main/java/com/fivet/buddy/mapper/EmoticonMapper.java
- src/main/java/com/fivet/buddy/services/ChatMemberService.java
- src/main/java/com/fivet/buddy/services/EmoticonService.java
- src/main/resources/mappers/chatMember-mapper.xml
- src/main/resources/mappers/emoticon-mapper.xml
- src/main/resources/static/css/team.css
- src/main/resources/templates/admin/adminEmoticon.html
- src/main/resources/templates/team/team.html
- src/main/resources/templates/team/teamChating.html
Feat : 채팅에서 이모티콘 사용 기능 추가, 채팅 회원 목록 출력 / New : ChatMemberListDto.java추가 (채팅방에서 채팅 회원 목록을 출력하기 위한 DTO)
Conflict : teamChating.html 풀 땡긴 후 충돌나서 해결
> (ver 9.0.0) Feat : 채팅에서 이모티콘 사용 기능 추가, 채팅 회원 목록 출력

- src/main/resources/templates/team/team.html
Feat : 토픽 "+" 버튼 매니저,부매니저만 보이게 하는 기능 추가
> (ver 9.6.2) Feat : 토픽 "+" 버튼 매니저,부매니저만 보이게 하는 기능 추가

- src/main/java/com/fivet/buddy/controller/ChatRoomController.java
- src/main/java/com/fivet/buddy/controller/TeamController.java
- src/main/java/com/fivet/buddy/dao/ChatMemberDAO.java
- src/main/java/com/fivet/buddy/mapper/ChatMemberMapper.java
- src/main/java/com/fivet/buddy/services/ChatMemberService.java
- src/main/resources/mappers/chatMember-mapper.xml
Fix : 채팅방 팀원 목록 출력 버그 수정
Does : 팀원 닉네임 변경 sysout 삭제
> (ver 9.9.8) Fix : 채팅방 팀원 목록 출력 버그 수정 / Does : 팀원 닉네임 변경 sysout 삭제

- src/main/java/com/fivet/buddy/controller/ChatRoomController.java
- src/main/resources/templates/team/team.html
- src/main/resources/templates/team/teamChating.html
> (ver 10.1.2) Feat : 토픽 생성 통합 작업

- src/main/resources/static/css/m-teamSetting.css
- src/main/resources/static/css/teamSetting.css
- src/main/resources/templates/member/myProfile.html
- src/main/resources/templates/team/teamSetting.html
Fix : 부매니저일 경우 등급 변경 불가능 버그 수정 / Refactor : 프로필 이미지 파일 용량 제한 크기 수정
> (ver 10.2.6) Fix : 부매니저일 경우 등급 변경 불가능 버그 수정 / Refactor : 프로필 이미지 파일 용량 제한 크기 수정

- src/main/java/com/fivet/buddy/controller/ChatRoomController.java
- src/main/java/com/fivet/buddy/dao/ChatRoomDAO.java
- src/main/java/com/fivet/buddy/mapper/ChatRoomMapper.java
- src/main/java/com/fivet/buddy/services/ChatRoomService.java
- src/main/resources/mappers/chatRoom-mapper.xml
- src/main/resources/templates/team/team.html
> (ver 11.0.5) Fix : 채팅방에 실 참여자인지 여부 체크 수정

- src/main/java/com/fivet/buddy/controller/ChatRoomController.java
- src/main/java/com/fivet/buddy/dao/ChatRoomDAO.java
- src/main/java/com/fivet/buddy/mapper/ChatRoomMapper.java
- src/main/java/com/fivet/buddy/services/ChatRoomService.java
- src/main/resources/mappers/chatRoom-mapper.xml
- src/main/resources/mappers/emoticon-mapper.xml
- src/main/resources/templates/team/teamChating.html
Feat : 채팅방 이름 출력 / Fix : 이모티콘 출력 정렬 수정
> (ver 11.0.8) Feat : 채팅방 이름 출력 / Fix : 이모티콘 출력 정렬 수정

- src/main/resources/templates/team/team.html
- src/main/resources/templates/team/teamChating.html
Fix : 채팅방 이름 출력, 팀원 닉네임 변경 버그 수정
> (ver 11.2.5) Fix : 채팅방 이름 출력, 팀원 닉네임 변경 버그 수정

- src/main/resources/templates/team/teamChating.html
Fix : 이모티콘 출력 오류 수정
Style : 이모티콘 크기 수정
> (ver 12.3.3) Fix : 이모티콘 출력 오류 수정 / Style : 이모티콘 크기 수정

- src/main/resources/templates/team/teamChating.html
- src/main/resources/templates/team/teamSetting.html
Fix : 이모티콘 출력 수정 / Docs : 팀 삭제 텍스트 수정
> (ver 12.4.3) Fix : 이모티콘 출력 수정 / Docs : 팀 삭제 텍스트 수정
